name: Hola Mundo
#on: [push, pull_request]  forma de colocar el evento o eventos

# forma de colocar los eventos indicando las ramas con las cuales se disparara.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: Hola Mundo
      run: echo 'Hola mundo'

    - name: cretae txt
      run: touch hola.txt
    
    - name: set txt
      run: echo 'Hola mundo' >> hola.txt
    
    - name: view txt
      run: more hola.txt


  other:
    runs-on: ubuntu-latest

    steps:
    - name: LS
      run: ls -a

  otherdepen:
    needs: [hola]
    runs-on: ubuntu-latest

    steps:
    - name: job depende de hola
      run: echo 'Dependo del Job Hola'

    - name: Checkout
      uses: actions/checkout@v4.2.2
    
    - name: LS
      run: |
             ls -a
             ls -a .github/workflows

# job en el cual utilizamos un script para instalar dependencias 

  scriptss:
    runs-on: ubuntu-latest
    needs: [otherdepen]
    steps:
 
      - name: LS
        run: ls -a /.github

      - name: utilizando scripts
        run: |
            ls
            chmod +x ./github/workflows/script.sh
            ./script.sh
