name: Hola Mundo
on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: Hola Mundo
      run: echo 'Hola mundo'

    - name: cretae txt
      run: touch hola.txt
    
    - name: set txt
      run: echo 'Hola mundo' >> hola.txt
    
    - name: view txt
      run: more hola.txt


  other:
    runs-on: ubuntu-latest

    steps:
    - name: LS
      run: ls -a

  otherdepen:
    needs: [hola]
    runs-on: ubuntu-latest

    steps:
    - name: job depende de hola
      run: echo 'Dependo del Job Hola'

      